#!/usr/bin/env bash
sudo rm init-ec2-and-deploy-service.sh > /dev/null && wget https://elasticbeanstalk-eu-west-1-533593536721.s3-eu-west-1.amazonaws.com/init-ec2-and-deploy-service.sh && sudo bash init-ec2-and-deploy-service.sh
