#!/bin/bash
# clear Data
rm -rf install/*

# configurationn
# TODO parameter filename
wget https://elasticbeanstalk-eu-west-1-533593536721.s3-eu-west-1.amazonaws.com/configuration-dependencies.sh
sh configuration-dependencies.sh

# TODO parameter fileName
wget https://elasticbeanstalk-eu-west-1-533593536721.s3-eu-west-1.amazonaws.com/dispatcher-install.zip

mv dispatcher-install.zip install.zip
unzip install.zip

cp install/* ~/*

rm -rf install/*

sh ~/init-dispatcher-server.sh
