#!/bin/bash
# the updates of this file should be sync to cookbook:https://github.com/xinzhang-hello/cookbook/blob/main/init-server/files/default/dispatcher-deployer
# clear Data
rm -rf install

# configurationn
# TODO parameter filename
wget https://tokyo-s3-bucket.s3-ap-northeast-1.amazonaws.com/configuration-dependencies.sh
sh configuration-dependencies.sh

# TODO parameter fileName
wget https://tokyo-s3-bucket.s3-ap-northeast-1.amazonaws.com/dispatcher-install.zip

mv dispatcher-install.zip install.zip
unzip install.zip

cp install/* /home/ubuntu/

rm -rf install
rm -rf install.zip

sh /home/ubuntu/init-dispatcher-server.sh
